package common.note;

import java.util.HashMap;
import java.util.Map;

import common.EntityTypeConstant;
import lli.constants.LliRequestTypeConstants;
import vpn.constants.VpnRequestTypeConstants;

public class CommonNoteConstants {
	
	public static final int ADVICE_NOTE_FOR_VPN_LINK = 1;
	public static final int ADVICE_NOTE_FOR_LLI_LINK = 10;
	
	public static final int VPN_INTERNAL_FR_RESPONSE = 4;
	public static final int LLI_INTERNAL_FR_RESPONSE = 8;
	
	public static final int VPN_EXTERNAL_FR_RESPONSE = 11;
	public static final int LLI_EXTERNAL_FR_RESPONSE = 14;
	
	
	public static HashMap<Integer, Integer> FR_RESPONSE = new HashMap<Integer, Integer>();
	public static Map<Integer, String> REQUEST_TYPE_TO_ADVICE_NOTE_NAME = new HashMap<Integer,String>();
	
	static {
		
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_REQUEST_ADVICE_NOTE, "Vpn new link advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( VpnRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_REQUEST_ADVICE_NOTE, "Vpn bandwidth upgradation advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( VpnRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_REQUEST_ADVICE_NOTE, "Vpn bandwidth downgrade advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( VpnRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_DISABLE, "Vpn disable link advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( VpnRequestTypeConstants.REQUEST_LINK_CLOSE.SYSTEM_REQUEST_ADVICE_NOTE, "Vpn link close advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( VpnRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_ENABLE, "Vpn link enable advice note" );
		
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( LliRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_REQUEST_ADVICE_NOTE, "Lli new connection advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( LliRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_REQUEST_ADVICE_NOTE, "Lli bandwidth upgrade advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( LliRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_REQUEST_ADVICE_NOTE, "Lli bandwidth downgrade advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( LliRequestTypeConstants.REQUEST_LINK_CLOSE.SYSTEM_REQUEST_ADVICE_NOTE, "Lli connection close advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( LliRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_DISABLE, "Lli connection disable advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( LliRequestTypeConstants.REQUEST_IPADDRESS.SYSTEM_REQUEST_ADVICE_NOTE, "Lli ip address request advice note" );
		REQUEST_TYPE_TO_ADVICE_NOTE_NAME.put( LliRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_ENABLE, "Lli connection enable advice note" );
	}
	
	static{
		
		FR_RESPONSE.put(EntityTypeConstant.VPN_LINK_NEAR_END, 2 );
		FR_RESPONSE.put(EntityTypeConstant.VPN_LINK_FAR_END, 3 );
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  4 );
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_NEW_LINK.GET_PREPARED_TO_GENERATE_DEMAND_NOTE,  4 );
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_WITH_INTERNAL_FR_NEGATIVE,  4 );
		
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_POP_CHANGE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  4 );
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_POP_CHANGE.GET_PREPARED_TO_GENERATE_DEMAND_NOTE,  4 );
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_POP_CHANGE.SYSTEM_RESPONSE_WITH_INTERNAL_FR_NEGATIVE,  4 );		
		
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_REQUEST_ADVICE_NOTE, 1 );
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_REQUEST_ADVICE_NOTE, 1 );
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_REQUEST_ADVICE_NOTE, 1 );
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_DISABLE, 1 );
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_LINK_CLOSE.SYSTEM_REQUEST_ADVICE_NOTE, 1 );
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_ENABLE,1 );
		
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  4 );
		FR_RESPONSE.put(-VpnRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  4 );
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  4 );
		FR_RESPONSE.put(-VpnRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  4 );
		
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_EXTERNAL_FR_OF_NEAR_END, 11 );
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_EXTERNAL_FR_OF_FAR_END, 11 );
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_EXACT_EXTERNAL_FR_OF_NEAR_END, 11); //
		FR_RESPONSE.put(VpnRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_EXACT_EXTERNAL_FR_OF_FAR_END, 11); //
		
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_POP_CHANGE.SYSTEM_RESPONSE_EXTERNAL_FR_OF_NEAR_END, 11 );
		FR_RESPONSE.put( VpnRequestTypeConstants.REQUEST_POP_CHANGE.SYSTEM_RESPONSE_EXTERNAL_FR_OF_FAR_END, 11 );
		
		
		FR_RESPONSE.put(EntityTypeConstant.LLI_LINK_FAR_END, 7 );
		
		FR_RESPONSE.put(LliRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
		FR_RESPONSE.put(LliRequestTypeConstants.REQUEST_NEW_LINK.GET_PREPARED_TO_GENERATE_DEMAND_NOTE,  8 );
		FR_RESPONSE.put(LliRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_WITH_INTERNAL_FR_NEGATIVE,  8 );
		FR_RESPONSE.put(LliRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
		FR_RESPONSE.put(-LliRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
		FR_RESPONSE.put(LliRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
		FR_RESPONSE.put(-LliRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
		FR_RESPONSE.put(-LliRequestTypeConstants.REQUEST_NEW_LINK.GET_PREPARED_TO_GENERATE_DEMAND_NOTE,  8 );
		FR_RESPONSE.put(LliRequestTypeConstants.REQUEST_CONNECTION_OWNERSHIP_CHANGE.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
		
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_RESPONSE_EXTERNAL_FR_OF_FAR_END, 14 );
		
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_NEW_LINK.SYSTEM_REQUEST_ADVICE_NOTE, 10 );
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_UPGRADE.SYSTEM_REQUEST_ADVICE_NOTE, 10 );
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_DOWNGRADE.SYSTEM_REQUEST_ADVICE_NOTE, 10 );
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_LINK_CLOSE.SYSTEM_REQUEST_ADVICE_NOTE, 10 );
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_DISABLE, 10 );
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_IPADDRESS.SYSTEM_REQUEST_ADVICE_NOTE, 10 );
		FR_RESPONSE.put( LliRequestTypeConstants.REQUEST_DISABLE_LINK.SYSTEM_REQUEST_ADVICE_NOTE_FOR_ENABLE,10 );
		
		FR_RESPONSE.put(LliRequestTypeConstants.REQUEST_IPADDRESS.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
		FR_RESPONSE.put(-LliRequestTypeConstants.REQUEST_IPADDRESS.SYSTEM_RESPONSE_WITH_INTERNAL_FR,  8 );
	}
	
}
