package common;

import java.util.HashMap;

public class RegistrantCategoryConstants {
	private  static final int MASK=(byte)0x01;
	private  static final int LONG_SIZE=8;
	private static final int MAXIMUM_TYPE=4;
	
	public static final int POSITIVE_LONG = MAXIMUM_TYPE * 8;
	//public static final int REGISTRANT_CATEGORY_IGW = 0;
	//public static final int REGISTRANT_CATEGORY_ICX = 1;
	public static final int REGISTRANT_CATEGORY_IIG = 1;
	public static final int REGISTRANT_CATEGORY_ISP = 2;
	public static final int REGISTRANT_CATEGORY_PROJECT = 3;
	public static final int REGISTRANT_CATEGORY_CORPORATE_BODY = 4;
	public static final int REGISTRANT_CATEGORY_OTHERS = POSITIVE_LONG - 2;
	
	
	public static final HashMap<Integer, String> DOMAIN_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> WEBHOSTING_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> IPADDRESS_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> COLOCATION_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> IIG_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> VPN_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> LLI_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> ADSL_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> NIX_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	public static final HashMap<Integer, String> DNSHOSTING_REGISTRANT_CATEGORY = new HashMap<Integer, String>();
	
	
	public static final HashMap<Integer, HashMap<Integer, String>> REGISTRANT_CATEGORY = new HashMap<Integer, HashMap<Integer, String>>();
	static
	{
		DOMAIN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		DOMAIN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		DOMAIN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		DOMAIN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		DOMAIN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		/*
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_EDUCATIONAL, "Educational");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_FINANCIAL, "Financial");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_ORGANIZATION, "Organization");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_NGO, "NGO");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_INSTITUTE, "Institute");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_PROJECT, "Project");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_IT, "IT");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_COMPANY, "Company");
		DOMAIN_REGISTRANT_CATEGORY.put(REG_TYPE_OTHERS, "Others");
		*/
		
		WEBHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		WEBHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		WEBHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		WEBHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		WEBHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		IPADDRESS_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		IPADDRESS_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		IPADDRESS_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		IPADDRESS_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		IPADDRESS_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		COLOCATION_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		COLOCATION_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		COLOCATION_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		COLOCATION_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		COLOCATION_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		IIG_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		IIG_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		IIG_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		IIG_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		IIG_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		//VPN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IGW, "IGW");
		//VPN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ICX, "ICX");
		VPN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		VPN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		VPN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		VPN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		VPN_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		LLI_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		LLI_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		LLI_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		LLI_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		LLI_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		ADSL_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		ADSL_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		ADSL_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		ADSL_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		ADSL_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		NIX_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		NIX_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		NIX_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		NIX_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		NIX_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		DNSHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_IIG, "IIG");
		DNSHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_ISP, "ISP");
		DNSHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_PROJECT, "Project");
		DNSHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_CORPORATE_BODY, "Corporate Body");
		DNSHOSTING_REGISTRANT_CATEGORY.put(REGISTRANT_CATEGORY_OTHERS, "Others");
		
		
		
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_DOMAIN, DOMAIN_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_WEBHOSTING, WEBHOSTING_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_IPADDRESS, IPADDRESS_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_COLOCATION, COLOCATION_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_IIG, IIG_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_VPN, VPN_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_LLI, LLI_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_ADSL, ADSL_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_NIX, NIX_REGISTRANT_CATEGORY);
		REGISTRANT_CATEGORY.put(ModuleConstants.Module_ID_DNSHOSTING, DNSHOSTING_REGISTRANT_CATEGORY);
		
	}
	
}
